### PR TITLE
Add badges to README

### PR DESCRIPTION
**Pull request by jcs090218**
Simple PR to add badges to README file. :)

### CODE REVIEW

**Comment by tarsius** [comment]
See the end off [Magit's README.md](https://github.com/magit/magit#acknowledgments) for my commentary on those badges. Especially the last one.

**Comment by jcs090218** [comment]
Hmm... is magic some how connect to hl-todo?

**Comment by tarsius** [comment]
No, but I was hoping that the placement and general silliness of the badges on magit's readme communicate the message that I think these badges are silly and a fad that I used to hope would go away some day, just like the "Best viewed with Netscape" and dancing baby gif fads eventually did. I don't feel strongly about this. I just don't think these badges add value and I therefore do not add them to my repositories.

**Comment by jcs090218** [comment]
Lol, okay. Good to know! Thanks!

**Pull request closed without merging**
